# Shorts Creator Configuration

# Video Processing Settings
video:
  # Output settings for social media platforms
  output_resolution: [1080, 1920]  # 9:16 aspect ratio (width, height)
  fps: 30
  quality: "ultra"  # low, medium, high, ultra
  codec: "h264"
  bitrate: "20M"  # Video bitrate
  audio_bitrate: "128k"

  # Input handling
  supported_formats: ["mp4", "mov", "avi", "mkv", "webm"]
  max_input_resolution: [3840, 2160]  # 4K max

# Scene Detection and Segmentation
segmentation:
  # Algorithm selection - choose which detection method to use
  algorithm: "optical_flow"    # "optical_flow" (FPV optimized, default) or "legacy" (old frame analysis)

  # Scene detection thresholds (balanced for detection + speed)
  scene_threshold: 0.08         # Lowered for better detection (was 0.15)
  motion_threshold: 0.02        # Lowered to catch more motion (was 0.05)

  # Frame sampling (frames per second to analyze) - much higher for proper detection
  frame_sample_rate: 2.0        # Dramatically increased - analyze 2 frames per second

  # Duration constraints (seconds) - optimized for 10-20 second segments
  min_duration: 8               # Minimum 8 seconds (was 3)
  max_duration: 25              # Allow up to 25 seconds for epic content
  target_duration: 15           # Target 15 seconds (was 12)

  # Dynamic duration settings - favor longer segments
  dynamic_duration: true        # Enable content-based duration
  quality_extension_threshold: 0.5  # More selective extension
  max_extension_duration: 10    # Reduced for faster processing

  # Overlap handling
  overlap_threshold: 0.25       # Slightly higher for better separation

  # Content filtering (more permissive to catch good content)
  content_filtering:
    avoid_low_motion: true      # Skip segments with very low motion (landings)
    min_motion_threshold: 0.015  # Much lower for better detection (was 0.03)
    avoid_static_scenes: true   # Skip static/boring scenes
    min_visual_interest: 0.12   # Much lower for better detection (was 0.2)

  # Scoring weights for segment selection (optimized for FPV footage)
  scoring:
    visual_interest: 0.6        # Higher weight for visual content
    motion_activity: 0.4        # Motion weight for action

# Color Grading and LUT Processing
color_grading:
  # Default settings
  default_lut: "luts/avata2.cube"
  lut_intensity: 1.0  # 0.0 to 1.0

  # Automatic adjustments
  auto_exposure: true
  auto_contrast: true
  auto_saturation: false

  # Manual adjustments (applied after LUT)
  exposure_offset: 0.0  # -2.0 to 2.0
  contrast_boost: 1.0   # 0.5 to 2.0
  saturation_boost: 1.0 # 0.0 to 2.0
  highlights: 0.0       # -1.0 to 1.0
  shadows: 0.0          # -1.0 to 1.0

  # Color space settings
  input_colorspace: "rec709"
  working_colorspace: "rec709"
  output_colorspace: "rec709"

# Audio Processing and Music
audio:
  # Background Music
  enable_music: true
  music_directory: "music/"
  music_volume: 1.0             # 0.0 to 1.0 (100% volume) - increased from 0.3
  fade_in_duration: 0.0         # Seconds - disabled to fix volume issue
  fade_out_duration: 0.0        # Seconds - disabled to fix volume issue

  # Music Selection (Enhanced AI-Powered System)
  random_selection: false       # Use intelligent selection instead of random
  preferred_genres: ["electronic", "cinematic", "upbeat", "rock"]  # Preferred genres for FPV

  # Intelligent Selection Settings
  intelligent_selection: true   # Enable AI-powered music selection
  variety_factor: 0.9          # 0.0-1.0, higher = more variety, lower = more consistent
  energy_preference: 0.7       # 0.0-1.0, preference for high-energy tracks
  tempo_preference: "upbeat"   # "slow", "medium", "upbeat", "fast"
  avoid_recent_limit: 20       # Avoid tracks used in last N videos

  # Library Analysis
  auto_analyze_library: true   # Automatically analyze new music files
  analysis_quality: "standard" # "fast", "standard", "comprehensive"
  cache_analysis: true         # Cache analysis results for faster processing

  # Audio Processing
  normalize_audio: false
  dynamic_range_compression: true
  noise_reduction: false        # Not needed for FPV footage

  # Mixing
  original_audio_volume: 0.0    # 0% - FPV footage usually has no useful audio
  music_ducking: false          # No speech to duck for

  # Beat Detection (for advanced features)
  beat_detection: true
  sync_cuts_to_beats: false     # Experimental feature

# Smart Cropping and Framing
cropping:
  # AI-powered cropping
  face_detection: true
  object_detection: true
  motion_tracking: true

  # Cropping behavior
  crop_padding: 0.1  # Extra space around subjects (0.0 to 0.5)
  smooth_tracking: true
  tracking_smoothness: 0.8  # 0.0 to 1.0

  # Safe areas (for platform UI)
  top_safe_area: 0.15    # 15% from top
  bottom_safe_area: 0.20 # 20% from bottom
  side_safe_area: 0.05   # 5% from sides

# Text and Captions
captions:
  # Speech-to-text
  enabled: true
  language: "en"
  confidence_threshold: 0.7

  # Styling
  font_family: "Arial Bold"
  font_size: 48
  font_color: "#FFFFFF"
  outline_color: "#000000"
  outline_width: 2

  # Positioning
  position: "bottom"  # top, center, bottom
  margin_bottom: 150  # pixels from bottom
  max_width: 0.8      # 80% of video width

# Performance Settings
performance:
  # Processing
  use_gpu: true
  gpu_device: 0
  num_threads: 12              # Increased for faster processing
  chunk_size: 2000             # Doubled for better efficiency

  # Hardware Encoding (NVENC/CUDA) - H264 for phone compatibility
  force_hardware_encoding: true    # Force hardware encoding, fail if not available
  hardware_decoder: true           # Use hardware decoder (CUDA) for input
  nvenc_preset: "p3"              # Fast preset (was p1) - balanced speed/quality
  nvenc_tuning: "ll"              # Low latency for speed (was hq)
  nvenc_multipass: "disabled"     # Disabled for speed (was qres)
  encoder_preference: "h264_nvenc" # Prefer H264 for phone compatibility

  # Memory management
  streaming_mode: true             # Enable streaming for faster processing
  max_memory_usage: "12GB"        # Increased memory allocation
  temp_dir: "/tmp/shorts_creator"  # Temporary processing directory

  # Caching
  enable_cache: true              # Enable frame caching for repeated processing
  cache_dir: ".cache"             # Cache directory
  cache_max_size: "5GB"           # Maximum cache size

  # Video processing optimizations - less aggressive downsampling
  downsampling_factor: 6          # Reduced from 8x to 4x for better quality
  max_frames_per_analysis: 2000   # Increased from 500 for better coverage
  parallel_processing: true      # Enable parallel frame processing

# Output Settings
output:
  # File naming
  naming_pattern: "{input_name}_short_{index}_{timestamp}"
  timestamp_format: "%Y%m%d_%H%M%S"

  # Directory structure
  create_subdirs: true
  subdir_pattern: "{date}/{input_name}"

  # Metadata
  include_metadata: true
  creator_tag: "ShortsCreator"

# Platform-Specific Settings
platforms:
  youtube_shorts:
    max_duration: 60
    recommended_duration: 30
    aspect_ratio: [9, 16]
    max_file_size: "100MB"

  tiktok:
    max_duration: 60
    recommended_duration: 15
    aspect_ratio: [9, 16]
    max_file_size: "72MB"

  instagram_reels:
    max_duration: 90
    recommended_duration: 30
    aspect_ratio: [9, 16]
    max_file_size: "100MB"

# Logging and Debugging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/shorts_creator.log"
  max_log_size: "10MB"
  backup_count: 5

  # Debug options
  save_intermediate_files: false
  debug_visualizations: false
  profile_performance: false

# Video Stabilization
stabilization:
  # FFmpeg vidstab settings
  enabled: false                    # Enable/disable stabilization by default
  ffmpeg_path: "ffmpeg"            # Path to ffmpeg executable (assumes it's in PATH)

  # Processing settings
  temp_dir: ".cache/stabilization" # Directory for temporary stabilized files
  keep_temp_files: false           # Keep temporary stabilized files after processing

  # Stabilization parameters (FFmpeg vidstab)
  smoothness: 10                   # Stabilization smoothness (higher = smoother, 1-100)
  shakiness: 5                     # Shakiness detection sensitivity (1-10)
  accuracy: 15                     # Motion detection accuracy (1-15, higher = more accurate)

  # Output settings
  output_suffix: "_stabilized"     # Suffix for stabilized video files
  preserve_original: true          # Keep original files when stabilizing

# Advanced Features
advanced:
  # Experimental features
  ai_thumbnail_generation: false
  trend_analysis: false
  multi_language_captions: false

  # Quality assessment
  quality_scoring: true
  engagement_prediction: true

  # Batch processing
  batch_size: 5
  parallel_processing: true